title: Yεrεmεe
iconURL: /assets/default-icon.png
theme: jekyll-theme-leaf

exclude: [SiteLocalTest.cmd, jekyll-theme-leaf.gemspec, Gemfile, Gemfile.lock]


# for a clean URL
# permalink: :slug

social:
  github: yeremee
  mail: yeremee@outlook.com

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N